### ISSUE TITLE
Consider using Tye

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Insights#17]
While developing locally you need to run both the `ExplorePackage.Website` website and the `ExplorePackages.Worker` Azure Function. It may be worthwhile to use project Tye to launch both of these projects together:

* https://github.com/dotnet/tye/blob/master/docs/tutorials/hello-tye/00_run_locally.md
* https://github.com/dotnet/tye/blob/master/docs/recipes/azure_functions.md

**Comment by joelverhagen** [comment]
Woah, nice idea. Haven't tried Tye yet but it looks great for the job!

**Comment by joelverhagen** [comment]
Consider how this relates to docker-compose. Example with Azurite:
https://github.com/microsoft/planetary-computer-apis/blob/main/docker-compose.yml
