### ISSUE TITLE
Update package manifest record to split tags

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Insights#22]
The `PackageManifestRecord` contains raw package tags as a string. Ideally these should be pre-processed into a parsed list for easier analysis. Currently you need to split tags with something like:

```
JverPackageManifests 
| where ResultType == "Available"
| extend Tags = translate(
    "  ", " ", translate(
    ",", " ", translate(
    ";", " ", translate(
    "\t", " ", Tags))))
| mv-expand split(Tags, " ")
| where isnotempty(Tags)
```

Tag splitting algorithm: https://github.com/NuGet/NuGet.Jobs/blob/376ac06e6e07d4ee8d1e28f6b2346e3891487496/src/Catalog/Helpers/Utils.cs#L37-L48

**Comment by joelverhagen** [comment]
I'm going close this and leave it as a query-time projection. There is no well spec'd way to parse tags so I think it's better to do it dynamically on the fly.

**Comment by loic-sharma** [comment]
Currently it's bothersome to answer a question like "How many packages have the tag windowsazureofficial": your options are to do a string contains 😰 or do that query-time projection 😥. IMO insights is particularly valuable since _anyone_ can jump into the data and get valuable learnings without being a NuGet expert. Tags is one area where NuGet knowledge is necessary, but perhaps that could mitigated by having two fields for both the "unprocessed" tags and the "parsed but maybe wrong" tags?

**Comment by joelverhagen** [comment]
Yeah, that's a great point! I think as long as the Markdown documentation clarifies the nuance of "parsed by maybe wrong", this can definitely work and add value. Thanks for pushing back 😃.
