### ISSUE TITLE
Add table for package signing certificate chains

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Insights#23]
Add a table to answer questions like:

* How many package signatures use a certificate that is revoked? What is the revocation date? How many packages are affected?
* How many package signatures use a certificate that chains to an untrusted root on Windows?
* How many package signatures use a certificate that is invalid?

This table should contain all certificates used to author sign, repository sign, or timestamp packages. This certificate data should be joinable against `JverPackageSignatures`.

Consider reusing: https://github.com/NuGet/NuGet.Jobs/blob/main/src/Validation.PackageSigning.ValidateCertificate/OnlineCertificateVerifier.cs

**Comment by joelverhagen** [comment]
One perspective of certificates to consider: https://github.com/NuGet/Engineering/issues/1430

**Comment by joelverhagen** [comment]
This is done. I haven't done anything with XCA yet. That can be added later if needed.
