### ISSUE TITLE
Test integration with Azurite and update docs

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Insights#30]
Per @khalidabuhakmeh:
https://twitter.com/buhakmeh/status/1394990191740346370

Blocked by:
- [x] https://github.com/Azure/Azurite/issues/790
- [x] https://github.com/Azure/Azurite/issues/791
- [x] https://github.com/Azure/Azurite/issues/792
- [x] https://github.com/Azure/Azurite/issues/793
- [x] https://github.com/Azure/Azurite/issues/794
- [x] https://github.com/Azure/Azurite/issues/1210
   - Workaround: sort on client side
- [x] https://github.com/Azure/Azurite/issues/1211
   - Workaround: used constant non-empty PK/RK
- [ ] https://github.com/Azure/Azurite/issues/959
   - Workaround: use service SAS instead of account SAS
- [x] https://github.com/Azure/Azurite/issues/1214
- [ ] https://github.com/Azure/Azurite/issues/1215
   - Workaround: this is not a blocker
- [x] https://github.com/Azure/Azurite/issues/1216
- [x] https://github.com/Azure/Azurite/issues/1227
   - Workaround: this is not a blocker
- [x] https://github.com/Azure/Azurite/issues/1228
- [x] https://github.com/Azure/Azurite/issues/1229
   - Workaround: change the unit test to just send back a wrong timestamp-based weak etag
- [x] https://github.com/Azure/Azurite/issues/1230
- [x] https://github.com/Azure/Azurite/issues/1232
- [x] https://github.com/Azure/Azurite/issues/1233
- [x] https://github.com/Azure/Azurite/issues/1234
- [x] https://github.com/Azure/Azurite/issues/1318
   - Workaround: this is not a blocker
- [x] https://github.com/Azure/Azurite/issues/1319
   - Workaround: disable the related test
- [x] https://github.com/Azure/Azurite/issues/1467
- [x] https://github.com/Azure/Azurite/issues/1465
- [x] https://github.com/Azure/Azurite/issues/1565

**Comment by edwin-huber** [comment]
I'll try to unblock all these ASAP.
We already have some PRs in the pipeline. 😄

**Comment by joelverhagen** [comment]
I have made a `ghcr.io/joelverhagen/azurite:edge` Docker image with all of the fixes I could hack together:
https://github.com/joelverhagen/Azurite/tree/edge

I used it temporarily in this PR which sets up a Tye config: https://github.com/NuGet/Insights/pull/41

**Comment by joelverhagen** [comment]
All tests are passing on Azurite 3.19.0!
